method: bayes
metric:
  goal: minimize
  name: valid/contrastive loss
parameters:
  lr:
    values:
      - 1e-04
      - 1e-05
      - 1e-06
  temperature:
    values:
      - 0.001
      - 0.005
      - 0.01
      - 0.05
      - 0.1
      - 0.3
program: main.py
