method: bayes
metric:
  goal: minimize
  name: validation/f1
parameters:
  temperature:
    values:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      - 0.7
      - 0.9
      - 1.5
      - 2
      - 2.5
      - 5
      - 7
      - 10
      - 15
      - 20
      - 30
      - 50
  num_augmentation:
    values:
      - 0
      - 1
      - 2
  lr:
    values:
      - 1e-05
      - 1e-06
program: main.py
