method: grid
metric:
  goal: minimize
  name: validation/f1
parameters:
  temperature:
    values:
      - 0.01
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      - 0.7
      - 0.8
      - 0.9
      - 1.0
      - 1.5
      - 1.7
      - 2
      - 2.5
      - 3
      - 5
      - 7
      - 10
      - 15
      - 20
      - 30
      - 50
  lr:
    values:
      - 1e-05
      - 1e-06
program: main.py
