method: bayes
metric:
  goal: maximize
  name: validation/f1
parameters:
  alpha:
    values:
      - 0.001
      - 0.01
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
      - 1
  lr:
    values:
      - 1e-04
      - 1e-05
      - 1e-06
  temperature:
    values:
      - 0.001
      - 0.01
      - 0.05
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
      - 2
program: main.py
